[package]
name = "sc-gui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "sc-gui"
path = "src/main.rs"

[dependencies]
sc-core.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
interprocess.workspace = true
crossbeam-channel.workspace = true
directories.workspace = true
eframe = { version = "0.29", default-features = false, features = ["glow", "wayland", "x11", "default_fonts"] }
egui = "0.29"
